name: GitHub 3D Contributions

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: hbonavota

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add .
          git commit -m "generate 3D contribution graph" || exit 0
          git push
